// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate() {
  return window['go']['main']['App']['ApplyUpdate']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function DetectDevice() {
  return window['go']['main']['App']['DetectDevice']();
}

export function DiagnoseDevice() {
  return window['go']['main']['App']['DiagnoseDevice']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDeviceConnected() {
  return window['go']['main']['App']['GetDeviceConnected']();
}

export function GetLanguage() {
  return window['go']['main']['App']['GetLanguage']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function IsStartupEnabled() {
  return window['go']['main']['App']['IsStartupEnabled']();
}

export function ListUSBDevices() {
  return window['go']['main']['App']['ListUSBDevices']();
}

export function PickDirectory(arg1) {
  return window['go']['main']['App']['PickDirectory'](arg1);
}

export function PollNow() {
  return window['go']['main']['App']['PollNow']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetStartupEnabled(arg1) {
  return window['go']['main']['App']['SetStartupEnabled'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function TestColor(arg1) {
  return window['go']['main']['App']['TestColor'](arg1);
}

export function TestOff() {
  return window['go']['main']['App']['TestOff']();
}

export function TestSound(arg1) {
  return window['go']['main']['App']['TestSound'](arg1);
}

export function TestThreshold(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestThreshold'](arg1, arg2, arg3);
}
