// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {statuslight} from '../models';
import {config} from '../models';
import {applog} from '../models';
import {main} from '../models';

export function ApplyUpdate():Promise<void>;

export function CheckForUpdate():Promise<updater.UpdateStatus>;

export function ClearLogs():Promise<void>;

export function DetectDevice():Promise<string>;

export function DiagnoseDevice():Promise<Array<statuslight.DebugInfo>>;

export function GetConfig():Promise<config.Config>;

export function GetDeviceConnected():Promise<boolean>;

export function GetLanguage():Promise<string>;

export function GetLogs():Promise<Array<applog.LogEntry>>;

export function GetStatus():Promise<main.Status>;

export function GetVersion():Promise<string>;

export function IsStartupEnabled():Promise<boolean>;

export function ListUSBDevices():Promise<Array<statuslight.USBDeviceInfo>>;

export function PickDirectory(arg1:string):Promise<string>;

export function PollNow():Promise<void>;

export function QuitApp():Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SetStartupEnabled(arg1:boolean):Promise<void>;

export function ShowWindow():Promise<void>;

export function TestColor(arg1:string):Promise<void>;

export function TestOff():Promise<void>;

export function TestSound(arg1:number):Promise<void>;

export function TestThreshold(arg1:string,arg2:boolean,arg3:boolean):Promise<void>;
